[build]
  command = "npm run build:netlify"
  publish = "dist"

[[redirects]]
  from = "/tournaments/*"
  to = "/tournaments/[slug].html"
  status = 200

[[redirects]]
  from = "/check-in/*"
  to = "/check-in/[slug].html"
  status = 200

[[redirects]]
  from = "/next"
  to = "/check-in/spades-summer-series"
  status = 302
